# Generated by Django 4.2.19 on 2025-08-23 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_branch_user_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('chef', 'Chef'), ('sales', 'Salesperson'), ('accountant', 'Accountant'), ('owner', 'Owner'), ('supervisor', 'Supervisor')], max_length=50),
        ),
    ]
