# Generated by Django 4.2.19 on 2025-09-23 19:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="image",
        ),
    ]
