# Generated by Django 4.2.19 on 2025-08-23 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('chef', 'Chef'), ('sales', 'Salesperson'), ('accountant', 'Accountant'), ('owner', 'Owner'), ('supervisor', 'Supervisor'), ('manager', 'Manager')], max_length=50),
        ),
    ]
