# Generated by Django 4.2.23 on 2025-07-19 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_remove_branch_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="branch",
            name="branch_name",
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name="branch",
            name="company",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.company",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="branch",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.branch",
            ),
        ),
    ]
