# Generated by Django 4.2.19 on 2025-09-01 12:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_branch_branch_name_branch_company_user_branch"),
        ("users", "0005_update_user_roles"),
    ]

    operations = []
