# Generated by Django 5.1.4 on 2025-01-08 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashierexpense',
            name='track_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
