# Generated by Django 4.2.23 on 2025-09-06 15:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="change",
            name="data_collected",
        ),
    ]
