# Generated by Django 4.2.19 on 2025-09-09 12:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="change",
            name="data_collected",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
