# Generated by Django 4.2.19 on 2025-09-30 15:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="change",
            old_name="data_collected",
            new_name="date_collected",
        ),
    ]
