# Generated by Django 4.2.23 on 2025-10-12 09:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="change",
            name="data_collected",
            field=models.DateTimeField(null=True),
        ),
    ]
