<<<<<<<< HEAD:finance/migrations/0003_remove_change_data_collected.py
# Generated by Django 4.2.23 on 2025-09-06 15:30
========
# Generated by Django 4.2.19 on 2025-09-23 19:24
>>>>>>>> e3c979211d5d355e3dc8245910d8d8668eebb65b:users/migrations/0003_remove_user_image.py

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
<<<<<<<< HEAD:finance/migrations/0003_remove_change_data_collected.py
        ("finance", "0002_initial"),
========
        ("users", "0002_user_image"),
>>>>>>>> e3c979211d5d355e3dc8245910d8d8668eebb65b:users/migrations/0003_remove_user_image.py
    ]

    operations = [
        migrations.RemoveField(
<<<<<<<< HEAD:finance/migrations/0003_remove_change_data_collected.py
            model_name="change",
            name="data_collected",
========
            model_name="user",
            name="image",
>>>>>>>> e3c979211d5d355e3dc8245910d8d8668eebb65b:users/migrations/0003_remove_user_image.py
        ),
    ]
