# Generated by Django 4.2.24 on 2025-09-04 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
        ("finance", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cashieraccount",
            name="branch",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.branch",
            ),
        ),
    ]
