# Generated by Django 4.2.24 on 2025-09-07 14:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0003_cashieraccount_branch"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cashieraccount",
            name="branch",
        ),
    ]
