# Generated by Django 4.2.19 on 2025-06-07 09:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0003_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cashierexpense",
            name="track_amount",
        ),
    ]
