# Generated by Django 4.2.19 on 2025-09-23 19:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0003_change_amount_collected_change_balance"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="change",
            name="data_collected",
        ),
    ]
