# Generated by Django 4.2.23 on 2025-09-06 15:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0003_remove_change_data_collected"),
    ]

    operations = [
        migrations.AddField(
            model_name="change",
            name="data_collected",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
