# Generated by Django 4.2.19 on 2025-02-20 14:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0003_change_cashier_give_alter_change_cashier_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cashierhandover",
            name="checkout_timestamp",
        ),
    ]
