# Generated by Django 4.2.23 on 2025-09-06 15:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0004_change_data_collected"),
    ]

    operations = [
        migrations.RenameField(
            model_name="change",
            old_name="data_collected",
            new_name="date_collected",
        ),
    ]
