# Generated by Django 4.2.19 on 2025-02-20 14:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0004_remove_cashierhandover_checkout_timestamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="cashierhandover",
            name="checkout_timestamp",
            field=models.DateTimeField(auto_now_add=True, default=""),
            preserve_default=False,
        ),
    ]
