# Generated by Django 4.2.19 on 2025-06-07 12:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0004_remove_cashierexpense_track_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="cashierexpense",
            name="track_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
