# Generated by Django 4.2.23 on 2025-06-30 17:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0005_cashierexpense_track_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="description",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
