# Generated by Django 4.2.19 on 2025-08-22 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_branch_user_branch'),
        ('finance', '0005_cashierexpense_track_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashbook',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.branch'),
        ),
        migrations.AddField(
            model_name='cashierexpense',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.branch'),
        ),
        migrations.AddField(
            model_name='cashup',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.branch'),
        ),
        migrations.AddField(
            model_name='expense',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.branch'),
        ),
        migrations.AddField(
            model_name='sale',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.branch'),
        ),
        migrations.AddField(
            model_name='sale',
            name='cash_type',
            field=models.CharField(blank=True, default='solid-cash', max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='transactionlog',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.branch'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
