# Generated by Django 4.2.23 on 2025-07-01 07:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0006_alter_expense_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cashierexpense",
            name="track_amount",
        ),
    ]
