# Generated by Django 4.2.23 on 2025-07-02 19:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0008_cashierexpense_track_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="cash_type",
            field=models.CharField(
                blank=True, default="solid-cash", max_length=12, null=True
            ),
        ),
    ]
