# Generated by Django 4.2.19 on 2025-09-01 12:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "finance",
            "0006_cashbook_branch_cashierexpense_branch_cashup_branch_and_more",
        ),
        (
            "finance",
            "0010_cashbook_branch_cashierexpense_branch_cashup_branch_and_more",
        ),
    ]

    operations = []
