# Generated by Django 4.2.24 on 2025-09-19 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AllocatedRawMaterials",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("remaining_quantity", models.FloatField(null=True)),
                ("quantity", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Budget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=15)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("description", models.TextField(blank=True, null=True)),
                ("confirmation", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="BudgetItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField()),
                (
                    "allocated_amount",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "spent_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
                ),
                ("reoccuring", models.BooleanField(default=False)),
                ("approove_by", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="CheckList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.BooleanField(default=False)),
                ("date", models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Declaration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kgs", models.FloatField(null=True)),
                ("expected", models.IntegerField(null=True)),
                ("declared", models.IntegerField(null=True)),
                ("sold", models.IntegerField(null=True)),
                ("staff", models.IntegerField(null=True)),
                ("left_over", models.IntegerField(null=True)),
                ("variance", models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Dish",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("portion_multiplier", models.FloatField()),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Fast food", "Fast food"),
                            ("Meat", "Meat"),
                            ("Starch", "Starch"),
                            ("Salad", "Salad"),
                        ],
                        max_length=255,
                    ),
                ),
                ("dish", models.BooleanField(default=True)),
                ("low_stock", models.IntegerField(default=10)),
                (
                    "image",
                    models.ImageField(
                        default="placeholder1.jpg", null=True, upload_to="meal_images/"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EndOfDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("done", models.BooleanField(default=False)),
                (
                    "total_sales",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "variance",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EndOfDayCashier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cashed_amount",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "sales",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "voids",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "expenses",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "variance",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EndOfDayItems",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dish_name", models.CharField(max_length=50)),
                ("total_portions", models.IntegerField(null=True)),
                ("total_sold", models.IntegerField(null=True)),
                ("staff_portions", models.IntegerField(null=True)),
                ("wastage", models.FloatField(null=True)),
                ("leftovers", models.FloatField(null=True)),
                ("servers_variance", models.FloatField(null=True)),
                ("declared", models.FloatField(null=True)),
                ("expected", models.FloatField(null=True)),
                ("recorded", models.BooleanField(default=False)),
                ("finished_product", models.CharField(null=True)),
                (
                    "product_cost",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "product_price",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                ("purchase_units", models.FloatField(null=True)),
                ("open_stock", models.FloatField(null=True)),
                ("close_stock", models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="EndOfDayStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("quantity", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("note", models.CharField(max_length=100, null=True)),
                ("quantity", models.FloatField()),
                (
                    "cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InventoryNotificationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                        ],
                        max_length=10,
                    ),
                ),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_read", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="LeftOvers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
                ),
                ("quantity", models.IntegerField(default=0)),
                (
                    "cash",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Logs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("stock in", "stock in"),
                            ("Stock update", "Stock update"),
                            ("edit", "Edit"),
                            ("sale", "Sale"),
                            ("declined", "Declined"),
                            ("write off", "write off"),
                            ("defective", "defective"),
                            ("activated", "activated"),
                            ("deactivated", "deactivated"),
                            ("removed", "removed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("quantity", models.FloatField()),
                ("total_quantity", models.FloatField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("description", models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Meal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("price", models.CharField(max_length=255)),
                ("deactivate", models.BooleanField(default=False)),
                ("meal", models.BooleanField(default=True)),
                (
                    "image",
                    models.ImageField(
                        default="placeholder1.jpg", null=True, upload_to="meal_images/"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MealCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="MinorProductionItems",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_quantity_per_kg", models.FloatField()),
                ("planned_quantity", models.FloatField()),
                ("expected_quantity", models.FloatField()),
                ("actual_quantity", models.FloatField(null=True)),
                (
                    "cost_per_kg",
                    models.DecimalField(decimal_places=2, default=1, max_digits=10),
                ),
                (
                    "total_cost",
                    models.DecimalField(decimal_places=2, default=1, max_digits=10),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MinorRawMaterials",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.FloatField()),
                ("quantity_left", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("is_read", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="OverrideHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_overrided", models.DateField(auto_now_add=True)),
                ("up", models.FloatField(null=True)),
                ("down", models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("quantity", models.FloatField()),
                ("cost", models.DecimalField(decimal_places=4, max_digits=10)),
                (
                    "price",
                    models.DecimalField(decimal_places=3, default=1, max_digits=10),
                ),
                (
                    "tax_type",
                    models.CharField(
                        choices=[
                            ("exempted", "Exempted"),
                            ("standard", "Standard"),
                            ("zero rated", "Zero Rated"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("min_stock_level", models.FloatField(default=0, null=True)),
                ("raw_material", models.BooleanField(default=False)),
                ("finished_product", models.BooleanField(default=False)),
                ("packaging", models.BooleanField(default=False)),
                ("description", models.TextField()),
                ("deactivate", models.BooleanField(default=False)),
                (
                    "image",
                    models.ImageField(
                        default="placeholder1.jpg",
                        null=True,
                        upload_to="product_images/",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Production",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateField(auto_now_add=True)),
                ("time_created", models.TimeField(auto_now_add=True)),
                ("status", models.BooleanField(default=False)),
                (
                    "production_plan_number",
                    models.CharField(default="", max_length=10, unique=True),
                ),
                ("declared", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="ProductionInventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="ProductionItems",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lf_brought_forward_quantity",
                    models.FloatField(blank=True, null=True),
                ),
                ("actual_quantity", models.FloatField(blank=True, null=True)),
                (
                    "total_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "remaining_raw_material",
                    models.FloatField(blank=True, default=0, null=True),
                ),
                ("declared", models.BooleanField(default=False)),
                ("left_overs", models.FloatField(blank=True, default=0, null=True)),
                ("wastage", models.FloatField(blank=True, default=0, null=True)),
                ("portions", models.FloatField(default=0, null=True)),
                ("staff_portions", models.FloatField(default=0, null=True)),
                ("planned_portions", models.FloatField(default=0, null=True)),
                ("portions_sold", models.FloatField(default=0, null=True)),
                ("allocated", models.BooleanField(default=False)),
                ("end_of_day_status", models.BooleanField(default=False)),
                (
                    "declared_quantity",
                    models.FloatField(blank=True, default=0, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductionLogs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("sale", "sale"),
                            ("stock in", "stock in"),
                            ("declared", "declared"),
                            ("to production", "to production"),
                        ],
                        max_length=20,
                    ),
                ),
                ("quantity", models.FloatField()),
                ("total_quantity", models.FloatField()),
                ("timestamp", models.DateField(auto_now_add=True)),
                ("description", models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ProductionRawMaterials",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="ProductionVariance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="PurchaseOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_number", models.CharField(max_length=100, unique=True)),
                ("order_date", models.DateTimeField(auto_now_add=True)),
                ("delivery_date", models.DateField(blank=True, null=True)),
                (
                    "total_cost",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("ordered", "Ordered"),
                            ("received", "Received"),
                            ("canceled", "Canceled"),
                        ],
                        default="pending",
                        max_length=50,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "discount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
                ),
                (
                    "tax_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
                ),
                (
                    "handling_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
                ),
                (
                    "other_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
                ),
                ("is_partial", models.BooleanField(default=False)),
                ("received", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="PurchaseOrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.FloatField()),
                ("unit_cost", models.DecimalField(decimal_places=2, max_digits=10)),
                ("received_quantity", models.FloatField(default=0)),
                ("received", models.BooleanField(default=False, null=True)),
                ("note", models.CharField(default="", max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Reorder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ordered", models.BooleanField(default=False)),
                ("approx_days", models.FloatField()),
                ("reorder_quantity", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="StockTake",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("actual_quantity", models.IntegerField(default=0)),
                ("variance", models.IntegerField(default=0)),
                ("notes", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="StockTakeItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recorded_quantity", models.IntegerField(default=0)),
                ("actual_quantity", models.IntegerField(default=0)),
                ("variance", models.IntegerField(default=0)),
                ("success", models.BooleanField(null=True)),
                ("accept_variance", models.BooleanField(default=False)),
                ("note", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("contact_name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
                ("address", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Supplies",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("dish", "Dish"), ("meal", "Meal")], max_length=10
                    ),
                ),
                ("quantity", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Transfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transfer_number", models.CharField(max_length=20, unique=True)),
                ("status", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="UnitOfMeasurement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unit_name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="TransferItems",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.FloatField()),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.product",
                    ),
                ),
                (
                    "transfer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="inventory.transfer",
                    ),
                ),
            ],
        ),
    ]
