# Generated by Django 4.2.23 on 2025-09-12 16:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="endofday",
            name="cashed_amount",
        ),
    ]
