# Generated by Django 4.2.19 on 2025-09-29 12:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="productioningriedients",
            old_name="expected_quantity",
            new_name="variance_cost",
        ),
        migrations.RenameField(
            model_name="productioningriedients",
            old_name="planned_quantity",
            new_name="variance_unit",
        ),
    ]
