# Generated by Django 4.2.19 on 2025-09-29 12:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "inventory",
            "0002_rename_expected_quantity_productioningriedients_variance_cost_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="productioningriedients",
            old_name="variance_unit",
            new_name="variance",
        ),
    ]
