# Generated by Django 4.2.19 on 2025-09-06 08:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("inventory", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="endofday",
            name="cashed_amount",
        ),
        migrations.CreateModel(
            name="EndOfDayCashier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cashed_amount",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "cashier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "end_of_day",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.endofday",
                    ),
                ),
            ],
            options={
                "unique_together": {("end_of_day", "cashier")},
            },
        ),
    ]
