# Generated by Django 4.2.19 on 2025-04-07 03:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ingredient",
            name="raw_material",
        ),
        migrations.AddField(
            model_name="dish",
            name="image",
            field=models.ImageField(
                default="placeholder.png", null=True, upload_to="meal_images/"
            ),
        ),
    ]
