# Generated by Django 4.2.23 on 2025-09-12 16:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0002_remove_endofday_cashed_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="endofday",
            name="cashed_amount",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
