# Generated by Django 5.1.4 on 2025-01-11 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_rename_raw_material_ingredient_minor_raw_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='minor_raw_material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.product'),
        ),
    ]
