# Generated by Django 4.2.23 on 2025-10-06 05:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="meal",
            name="dish",
        ),
    ]
