# Generated by Django 5.1.4 on 2025-01-11 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_ingredient_minor_raw_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='raw_material',
            field=models.CharField(null=True),
        ),
    ]
