# Generated by Django 4.2.19 on 2025-09-06 08:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("inventory", "0003_purchaseorder_cashiers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="purchaseorder",
            name="cashiers",
        ),
        migrations.AddField(
            model_name="endofday",
            name="cashiers",
            field=models.ManyToManyField(
                null=True, related_name="po_cashiers", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
