# Generated by Django 4.2.19 on 2025-09-23 19:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0003_rename_cashed_amount_endofday_variance_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dish",
            name="low_stock_time",
        ),
        migrations.RemoveField(
            model_name="meal",
            name="low_stock_time",
        ),
        migrations.RemoveField(
            model_name="product",
            name="packaging",
        ),
        migrations.RemoveField(
            model_name="product",
            name="updated_at",
        ),
    ]
