# Generated by Django 4.2.19 on 2025-04-08 11:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0003_remove_ingredient_raw_material_dish_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingredient",
            name="cost",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
