# Generated by Django 4.2.23 on 2025-10-06 05:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0003_remove_meal_dish"),
    ]

    operations = [
        migrations.AddField(
            model_name="meal",
            name="dish",
            field=models.ManyToManyField(related_name="dishes", to="inventory.dish"),
        ),
    ]
