# Generated by Django 5.1.4 on 2025-01-08 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_budget_confirmation_remove_budget_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budgetitem',
            name='budget',
        ),
        migrations.DeleteModel(
            name='Budget',
        ),
    ]
