# Generated by Django 4.2.19 on 2025-09-29 12:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0003_rename_variance_unit_productioningriedients_variance"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ProductionIngriedients",
        ),
    ]
