# Generated by Django 4.2.19 on 2025-09-23 22:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0004_remove_dish_low_stock_time_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="dailylowstockflag",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="dailylowstockflag",
            name="current_portions",
        ),
        migrations.RemoveField(
            model_name="dailylowstockflag",
            name="date",
        ),
        migrations.RemoveField(
            model_name="dailylowstockflag",
            name="dish",
        ),
        migrations.RemoveField(
            model_name="dailylowstockflag",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="dailylowstockflag",
            name="meal",
        ),
        migrations.RemoveField(
            model_name="dailylowstockflag",
            name="threshold",
        ),
        migrations.RemoveField(
            model_name="dailylowstockflag",
            name="time_detected",
        ),
    ]
