# Generated by Django 4.2.23 on 2025-10-10 12:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0004_meal_dish"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productionitems",
            name="production",
        ),
    ]
