# Generated by Django 5.1.4 on 2025-01-08 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_remove_budgetitem_budget_delete_budget'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BudgetItem',
        ),
    ]
