# Generated by Django 4.2.19 on 2025-09-29 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0004_delete_productioningriedients"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductionIngriedients",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_quantity_per_kg", models.FloatField()),
                ("variance_cost", models.FloatField()),
                ("variance", models.FloatField()),
                ("actual_quantity", models.FloatField(null=True)),
                (
                    "cost_per_kg",
                    models.DecimalField(decimal_places=2, default=1, max_digits=10),
                ),
                (
                    "total_cost",
                    models.DecimalField(decimal_places=2, default=1, max_digits=10),
                ),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.product",
                    ),
                ),
                (
                    "production",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.production",
                    ),
                ),
            ],
        ),
    ]
