# Generated by Django 4.2.19 on 2025-06-07 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0004_ingredient_cost"),
    ]

    operations = [
        migrations.AddField(
            model_name="productionitems",
            name="end_of_day_status",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="OverrideHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_overrided", models.DateField(auto_now_add=True)),
                ("up", models.FloatField(null=True)),
                ("down", models.FloatField(null=True)),
                (
                    "raw_material_overrided",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EndOfDayStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("quantity", models.IntegerField(default=0)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.product",
                    ),
                ),
            ],
        ),
    ]
