# Generated by Django 4.2.18 on 2025-01-25 10:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0004_ingredient_raw_material"),
    ]

    operations = [
        migrations.AddField(
            model_name="budgetitem",
            name="approove_by",
            field=models.DateField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="budgetitem",
            name="reoccuring",
            field=models.BooleanField(default=False),
        ),
    ]
