# Generated by Django 4.2.19 on 2025-09-06 08:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0005_remove_endofday_cashed_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="endofdaycashier",
            name="expenses",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="endofdaycashier",
            name="sales",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="endofdaycashier",
            name="voids",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
