# Generated by Django 4.2.23 on 2025-10-10 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0005_remove_productionitems_production"),
    ]

    operations = [
        migrations.AddField(
            model_name="productionitems",
            name="production",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory.production",
            ),
        ),
    ]
