# Generated by Django 4.2.19 on 2025-09-23 22:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0005_alter_dailylowstockflag_unique_together_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DailyLowStockFlag",
        ),
    ]
