# Generated by Django 4.2.19 on 2025-08-22 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_branch_user_branch'),
        ('inventory', '0005_productionitems_end_of_day_status_overridehistory_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productionitems',
            old_name='declared_quantity',
            new_name='planned_portions',
        ),
        migrations.AddField(
            model_name='dish',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.branch'),
        ),
        migrations.AddField(
            model_name='dish',
            name='low_stock',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='endofday',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.branch'),
        ),
        migrations.AddField(
            model_name='endofdaystock',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.branch'),
        ),
        migrations.AddField(
            model_name='meal',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.branch'),
        ),
        migrations.AddField(
            model_name='product',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.branch'),
        ),
        migrations.AddField(
            model_name='production',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.branch'),
        ),
        migrations.AddField(
            model_name='productionlogs',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.branch'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.branch'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.branch'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.branch'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='category',
            field=models.CharField(choices=[('Fast food', 'Fast food'), ('Meat', 'Meat'), ('Starch', 'Starch'), ('Salad', 'Salad')], max_length=255),
        ),
        migrations.AlterField(
            model_name='dish',
            name='image',
            field=models.ImageField(default='placeholder1.jpg', null=True, upload_to='meal_images/'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='image',
            field=models.ImageField(default='placeholder1.jpg', null=True, upload_to='meal_images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='placeholder1.jpg', null=True, upload_to='product_images/'),
        ),
        migrations.CreateModel(
            name='ProductionVariance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.production')),
            ],
        ),
    ]
