# Generated by Django 4.2.19 on 2025-02-06 15:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0006_leftovers"),
    ]

    operations = [
        migrations.AddField(
            model_name="leftovers",
            name="total_amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
        ),
        migrations.AlterField(
            model_name="leftovers",
            name="date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
