# Generated by Django 4.2.23 on 2025-07-19 12:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0006_productionvariance"),
    ]

    operations = [
        migrations.RenameField(
            model_name="productionitems",
            old_name="declared_quantity",
            new_name="planned_portions",
        ),
        migrations.AddField(
            model_name="dish",
            name="low_stock",
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name="dish",
            name="category",
            field=models.CharField(
                choices=[
                    ("Fast food", "Fast food"),
                    ("Meat", "Meat"),
                    ("Starch", "Starch"),
                    ("Salad", "Salad"),
                ],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="dish",
            name="image",
            field=models.ImageField(
                default="placeholder1.jpg", null=True, upload_to="meal_images/"
            ),
        ),
        migrations.AlterField(
            model_name="meal",
            name="image",
            field=models.ImageField(
                default="placeholder1.jpg", null=True, upload_to="meal_images/"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                default="placeholder1.jpg", null=True, upload_to="product_images/"
            ),
        ),
    ]
