# Generated by Django 4.2.19 on 2025-09-06 10:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0006_endofdaycashier_expenses_endofdaycashier_sales_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="endofdaycashier",
            name="variance",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
