# Generated by Django 4.2.19 on 2025-02-08 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("inventory", "0007_leftovers_total_amount_alter_leftovers_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="leftovers",
            name="cash",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
        ),
        migrations.AddField(
            model_name="leftovers",
            name="cashier",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="meal",
            name="image",
            field=models.ImageField(
                default="placeholder.png", null=True, upload_to="meal_images/"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(
                default="placeholder.png", null=True, upload_to="product_images/"
            ),
        ),
    ]
