# Generated by Django 4.2.19 on 2025-09-23 22:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0007_dailylowstockflag"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="packaging",
            field=models.BooleanField(default=False),
        ),
    ]
