# Generated by Django 4.2.23 on 2025-07-19 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_branch_branch_name_branch_company_user_branch"),
        (
            "inventory",
            "0007_rename_declared_quantity_productionitems_planned_portions_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="dish",
            name="branch",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.branch",
            ),
        ),
        migrations.AddField(
            model_name="endofday",
            name="branch",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.branch",
            ),
        ),
        migrations.AddField(
            model_name="endofdaystock",
            name="branch",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.branch",
            ),
        ),
        migrations.AddField(
            model_name="meal",
            name="branch",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.branch",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="branch",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.branch",
            ),
        ),
        migrations.AddField(
            model_name="production",
            name="branch",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.branch",
            ),
        ),
        migrations.AddField(
            model_name="productionlogs",
            name="branch",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.branch",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="branch",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.branch",
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="branch",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.branch",
            ),
        ),
        migrations.AddField(
            model_name="transfer",
            name="branch",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.branch",
            ),
        ),
    ]
