# Generated by Django 4.2.23 on 2025-10-10 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0007_remove_productionitems_dish"),
    ]

    operations = [
        migrations.AddField(
            model_name="productionitems",
            name="dish",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory.dish",
            ),
        ),
    ]
