# Generated by Django 4.2.19 on 2025-09-23 23:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0008_product_packaging"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="updatd_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
