# Generated by Django 4.2.19 on 2025-02-10 14:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0008_leftovers_cash_leftovers_cashier_meal_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="raw_material",
            field=models.CharField(blank=True, null=True),
        ),
    ]
