# Generated by Django 4.2.23 on 2025-08-15 13:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0008_dish_branch_endofday_branch_endofdaystock_branch_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dish",
            name="branch",
        ),
    ]
