# Generated by Django 4.2.19 on 2025-09-23 23:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0009_product_updatd_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="updatd_at",
            new_name="updated_at",
        ),
    ]
