# Generated by Django 4.2.23 on 2025-08-15 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_branch_branch_name_branch_company_user_branch"),
        ("inventory", "0009_remove_dish_branch"),
    ]

    operations = [
        migrations.AddField(
            model_name="dish",
            name="branch",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.branch",
            ),
        ),
    ]
