# Generated by Django 4.2.23 on 2025-10-10 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
        ("inventory", "0009_remove_production_branch"),
    ]

    operations = [
        migrations.AddField(
            model_name="production",
            name="branch",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.branch",
            ),
        ),
    ]
