# Generated by Django 4.2.19 on 2025-02-10 14:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0009_alter_ingredient_raw_material"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ingredient",
            name="raw_material",
        ),
    ]
