# Generated by Django 4.2.19 on 2025-09-01 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_merge_20250901_1436"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("inventory", "0010_dish_branch"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockTake",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("actual_quantity", models.IntegerField(default=0)),
                ("variance", models.IntegerField(default=0)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "branch",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.branch",
                    ),
                ),
                (
                    "conductor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "users",
                    models.ManyToManyField(
                        null=True,
                        related_name="stock_users",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="productionlogs",
            name="branch",
        ),
        migrations.AddField(
            model_name="productionitems",
            name="declared_quantity",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="StockTakeItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recorded_quantity", models.IntegerField(default=0)),
                ("actual_quantity", models.IntegerField(default=0)),
                ("variance", models.IntegerField(default=0)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.product",
                    ),
                ),
                (
                    "stock_take",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="inventory.stocktake",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Declaration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kgs", models.FloatField(null=True)),
                ("expected", models.IntegerField(null=True)),
                ("declared", models.IntegerField(null=True)),
                ("sold", models.IntegerField(null=True)),
                ("staff", models.IntegerField(null=True)),
                ("left_over", models.IntegerField(null=True)),
                ("variance", models.FloatField(null=True)),
                (
                    "dish",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.dish",
                    ),
                ),
                (
                    "meal",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.meal",
                    ),
                ),
            ],
        ),
    ]
