# Generated by Django 4.2.23 on 2025-08-30 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0010_dish_branch"),
    ]

    operations = [
        migrations.CreateModel(
            name="Declaration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kgs", models.FloatField(null=True)),
                ("expected", models.IntegerField(null=True)),
                ("declared", models.IntegerField(null=True)),
                ("sold", models.IntegerField(null=True)),
                ("staff", models.IntegerField(null=True)),
                ("left_over", models.IntegerField(null=True)),
                ("variance", models.FloatField(null=True)),
                (
                    "dish",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.dish",
                    ),
                ),
                (
                    "meal",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.meal",
                    ),
                ),
            ],
        ),
    ]
