# Generated by Django 4.2.19 on 2025-09-23 23:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0010_rename_updatd_at_product_updated_at"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MealDishLowStock",
        ),
    ]
