# Generated by Django 4.2.23 on 2025-10-10 13:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0010_production_branch"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="minorproductionitems",
            name="minor_raw_material",
        ),
    ]
