# Generated by Django 4.2.19 on 2025-09-09 14:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0010_module_emailnotifications_user_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EmailNotifications",
        ),
        migrations.DeleteModel(
            name="Module",
        ),
    ]
