# Generated by Django 4.2.19 on 2025-02-20 14:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0010_remove_ingredient_raw_material"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingredient",
            name="raw_material",
            field=models.CharField(null=True),
        ),
    ]
