# Generated by Django 4.2.23 on 2025-10-13 11:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0011_remove_minorproductionitems_minor_raw_material"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="packaging",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
