# Generated by Django 4.2.19 on 2025-02-20 14:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0011_ingredient_raw_material"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="image",
        ),
    ]
