# Generated by Django 4.2.19 on 2025-09-09 15:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0011_delete_emailnotifications_delete_module"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="packaging",
            field=models.BooleanField(default=False),
        ),
    ]
