# Generated by Django 4.2.19 on 2025-09-23 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0011_delete_mealdishlowstock"),
    ]

    operations = [
        migrations.CreateModel(
            name="MealDishLowStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.TimeField()),
                ("end_time", models.TimeField(blank=True, null=True)),
                ("portions", models.IntegerField()),
                (
                    "dish",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.dish",
                    ),
                ),
                (
                    "meal",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.meal",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="dish",
            name="low_stock_time",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dish_notification",
                to="inventory.mealdishlowstock",
            ),
        ),
        migrations.AddField(
            model_name="meal",
            name="low_stock_time",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="meal_notification",
                to="inventory.mealdishlowstock",
            ),
        ),
    ]
