# Generated by Django 4.2.19 on 2025-09-01 12:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0011_stocktake_remove_productionlogs_branch_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stocktakeitem",
            name="product",
        ),
        migrations.RemoveField(
            model_name="stocktakeitem",
            name="stock_take",
        ),
        migrations.DeleteModel(
            name="StockTake",
        ),
        migrations.DeleteModel(
            name="StockTakeItem",
        ),
    ]
