# Generated by Django 4.2.19 on 2025-09-24 00:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0012_mealdishlowstock_dish_low_stock_time_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="endofday",
            name="total_sales",
        ),
    ]
