# Generated by Django 4.2.19 on 2025-02-20 14:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0012_remove_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(
                default="placeholder.png", null=True, upload_to="product_images/"
            ),
        ),
    ]
