# Generated by Django 4.2.23 on 2025-10-13 11:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0012_product_packaging"),
    ]

    operations = [
        migrations.DeleteModel(
            name="InventoryNotificationLog",
        ),
    ]
