# Generated by Django 4.2.19 on 2025-02-20 15:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0013_product_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="meal",
            name="image",
        ),
    ]
