# Generated by Django 4.2.19 on 2025-09-24 00:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0013_remove_endofday_total_sales"),
    ]

    operations = [
        migrations.AddField(
            model_name="endofday",
            name="total_sales",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
