# Generated by Django 4.2.19 on 2025-09-01 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_merge_20250901_1436"),
        ("inventory", "0013_stocktake_stocktakeitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="logs",
            name="branch",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.branch",
            ),
        ),
    ]
