# Generated by Django 4.2.19 on 2025-09-15 10:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0003_add_branch_to_productionlogs"),
        ("inventory", "0014_product_updated_at"),
    ]

    operations = []
