# Generated by Django 4.2.19 on 2025-02-20 15:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0014_remove_meal_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="meal",
            name="image",
            field=models.ImageField(
                default="placeholder.png", null=True, upload_to="meal_images/"
            ),
        ),
    ]
