# Generated by Django 4.2.19 on 2025-09-24 00:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0014_endofday_total_sales"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="endofday",
            name="variance",
        ),
    ]
