# Generated by Django 4.2.19 on 2025-09-01 16:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0014_logs_branch"),
    ]

    operations = [
        migrations.AddField(
            model_name="stocktakeitem",
            name="success",
            field=models.BooleanField(null=True),
        ),
    ]
