# Generated by Django 4.2.19 on 2025-09-24 00:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0015_remove_endofday_variance"),
    ]

    operations = [
        migrations.AddField(
            model_name="endofday",
            name="variance",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
