# Generated by Django 4.2.19 on 2025-09-01 23:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0015_stocktakeitem_success"),
    ]

    operations = [
        migrations.AddField(
            model_name="stocktakeitem",
            name="accept_variance",
            field=models.BooleanField(default=False),
        ),
    ]
