# Generated by Django 4.2.19 on 2025-09-18 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0015_merge_20250915_1206"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productionlogs",
            name="branch",
        ),
        migrations.CreateModel(
            name="MealDishNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.TimeField()),
                ("portions", models.IntegerField()),
                (
                    "dish",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.dish",
                    ),
                ),
                (
                    "meal",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.meal",
                    ),
                ),
            ],
        ),
    ]
