# Generated by Django 4.2.19 on 2025-09-01 23:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0016_stocktakeitem_accept_variance"),
    ]

    operations = [
        migrations.AddField(
            model_name="stocktakeitem",
            name="note",
            field=models.TextField(blank=True, null=True),
        ),
    ]
