# Generated by Django 4.2.19 on 2025-09-24 01:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0016_endofday_variance"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Supplies",
        ),
    ]
