# Generated by Django 4.2.19 on 2025-09-18 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0016_remove_productionlogs_branch_mealdishnotification"),
    ]

    operations = [
        migrations.AddField(
            model_name="dish",
            name="notification",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dish_notification",
                to="inventory.mealdishnotification",
            ),
        ),
        migrations.AddField(
            model_name="meal",
            name="notification",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="meal_notification",
                to="inventory.mealdishnotification",
            ),
        ),
    ]
