# Generated by Django 4.2.19 on 2025-09-02 05:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0017_stocktakeitem_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="endofdayitems",
            name="servers_variance",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="endofdayitems",
            name="expected",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="endofdayitems",
            name="leftovers",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="endofdayitems",
            name="staff_portions",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="endofdayitems",
            name="total_portions",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="endofdayitems",
            name="total_sold",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="endofdayitems",
            name="wastage",
            field=models.FloatField(null=True),
        ),
    ]
