# Generated by Django 4.2.19 on 2025-09-19 17:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0017_dish_notification_meal_notification"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="MealDishNotification",
            new_name="MealDishLowStock",
        ),
        migrations.RenameField(
            model_name="dish",
            old_name="notification",
            new_name="low_stock_time",
        ),
        migrations.RenameField(
            model_name="meal",
            old_name="notification",
            new_name="low_stock_time",
        ),
    ]
