# Generated by Django 4.2.23 on 2025-09-29 14:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0003_endofday_cashed_amount"),
        ("inventory", "0018_supplies"),
    ]

    operations = []
