# Generated by Django 4.2.19 on 2025-09-02 05:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0018_endofdayitems_servers_variance_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="endofdayitems",
            name="declared",
            field=models.FloatField(null=True),
        ),
    ]
