# Generated by Django 4.2.19 on 2025-09-22 15:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0018_rename_mealdishnotification_mealdishlowstock_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mealdishlowstock",
            name="end_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
