# Generated by Django 4.2.19 on 2025-09-02 08:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0019_endofdayitems_declared"),
    ]

    operations = [
        migrations.AddField(
            model_name="endofdayitems",
            name="recorded",
            field=models.BooleanField(default=False),
        ),
    ]
