# Generated by Django 4.2.19 on 2025-09-22 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0019_mealdishlowstock_end_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyLowStockFlag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("time_detected", models.TimeField()),
                ("current_portions", models.IntegerField()),
                ("threshold", models.IntegerField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "dish",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.dish",
                    ),
                ),
                (
                    "meal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.meal",
                    ),
                ),
            ],
            options={
                "unique_together": {("dish", "meal", "date")},
            },
        ),
    ]
