# Generated by Django 4.2.19 on 2025-09-02 09:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0020_endofdayitems_recorded"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productionitems",
            name="declared_quantity",
        ),
    ]
