# Generated by Django 4.2.19 on 2025-09-02 09:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0021_remove_productionitems_declared_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="productionitems",
            name="declared_quantity",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
