# Generated by Django 4.2.19 on 2025-09-04 10:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0022_productionitems_declared_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="endofdayitems",
            name="finished_product",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
