# Generated by Django 4.2.19 on 2025-09-04 10:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0023_endofdayitems_finished_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="endofdayitems",
            name="finished_product",
            field=models.CharField(null=True),
        ),
    ]
