# Generated by Django 4.2.19 on 2025-09-04 12:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0024_alter_endofdayitems_finished_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="endofdayitems",
            name="product_cost",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="endofdayitems",
            name="product_price",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="endofdayitems",
            name="purchase_units",
            field=models.FloatField(null=True),
        ),
    ]
