# Generated by Django 4.2.19 on 2025-09-04 13:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0025_endofdayitems_product_cost_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="endofdayitems",
            name="close_stock",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="endofdayitems",
            name="open_stock",
            field=models.FloatField(null=True),
        ),
    ]
