# Generated by Django 4.2.19 on 2025-04-12 10:33

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Authorization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("auth_date", models.DateField(auto_now_add=True)),
                ("auth_granted", models.BooleanField(default=False)),
            ],
        ),
    ]
