# Generated by Django 4.2.19 on 2025-06-07 09:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pos", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Authorization",
            new_name="SaleAuthorization",
        ),
    ]
